### ISSUE TITLE
Tratar variações de produto

### ISSUE THREAD

**Issue by vitorrgg** [ecomclub/widget-product#17]
Tratar no widget as `variations` do [produto](https://developers.e-com.plus/docs/api/#/store/products/products). Isso inclui: 

- Renderizar todas variações, e suas devidas opções que devem ser escolhidas pelo usuário;
- Recalcular o preço de acordo com as opções do usuário;
- Trocar a imagem de acordo com a opção selecionada caso aplicável

**Comment by leomp12** [comment]
https://github.com/ecomclub/widget-product/issues/6
